Program
..FuncDecl
....FuncHeader
......Id(factorial)
......Int
......FuncParams
........ParamDecl
..........Int
..........Id(n)
....FuncBody
......If
........Eq
..........Id(n)
..........IntLit(0)
........Block
..........Return
............IntLit(1)
........Block
......Return
........Mul
..........Id(n)
..........Call
............Id(factorial)
............Sub
..............Id(n)
..............IntLit(1)
..FuncDecl
....FuncHeader
......Id(main)
......FuncParams
....FuncBody
......VarDecl
........Int
........Id(argument)
......ParseArgs
........Id(argument)
........IntLit(1)
......Print
........Call
..........Id(factorial)
..........Id(argument)
